### PR TITLE
Create Channel object automatically if it not exist

### PR DESCRIPTION
**Pull request by SchumyHao**
Hi @Scrounger 
This is a PR for #6

### CODE REVIEW

**Comment by Scrounger** [comment]
Please explmain how does this work?
This will always creates a channel if its not exists?

**Comment by SchumyHao** [comment]
Yeap
`setObjectNotExistsAsync` will create a object if not exist.
So I use this to create a channel object for linked state object.

image
After add this patch, I can set room and function enum for this channel

**Comment by SchumyHao** [comment]
@Scrounger  Do you think this patch can me merged?

**Comment by Scrounger** [comment]
at the moment i am not clear about this is the right solution.
With this solution it will always create a channel or if it still exist, it will be overwritten.

At my opinion it would be better to have an integration in the admin adapter:
https://github.com/ioBroker/ioBroker.admin/issues/415

Alternative could be a button to clone channels, devices etc. in the linkeddevices adapter settings.
I have to think about that.

**Comment by SchumyHao** [comment]
setObjectNotExistsAsync  only create object if it is not exist.

**Comment by SchumyHao** [comment]
Without channel object, type-detector will not work perfactly

**Pull request merged**
